### ISSUE TITLE
Extract the "demo" as a separate project

### ISSUE THREAD

**Issue by thePanz** [netgen/query-translator#10]
Provide the demo as a separated project, using `composer create-project`

**Comment by thePanz** [comment]
See https://github.com/thePanz/query-translator-demo
It should belong to the `netgen` organization IHMO.
Let me know

**Comment by pspanja** [comment]
Thanks @thePanz, I think this makes sense 🙂 
You can transfer the repo to `netgen`, I'll accept it.

**Comment by thePanz** [comment]
i tried, but I got: `You don’t have the permission to create repositories on netgen `.
Can you fork it in the `netgen` org, I'll delete my repository afterwords

**Comment by pspanja** [comment]
OK, forked to https://github.com/netgen/query-translator-demo

**Comment by thePanz** [comment]
Thanks @pspanja ! I deleted my repository now!
I guess this MR is now ready for review :)
